### ISSUE TITLE
Tüm il, ilçe, mahalle, köy, cadde-sokak vs. bilgilerin tamamını dönmek

### ISSUE THREAD

**Issue by yasinatesim** [nurullahisik/php-uavt-adreskodu-botu#1]
Merhabalar,

Türkiyede yer alan tüm il, ilçe, mahalle, köy, cadde-sokak vs. bilgilerin tamamını bir json çıktısı olarak almak istiyorum. 

Yardımcı olabilir misiniz lütfen?

Bu arada, geliştirdiğiniz botu çok beğendim, elinize sağlık. Başarılarınızın devamını dilerim.

**Comment by nurullahisik** [comment]
Merhaba, öncelikle ilginiz için teşekkür ederim.

Türkiye'deki tüm il-ilçe, mahalle, cadde-sokak bilgilerini json ve sql scripti haline getirme fikri uzun zamandır aklımda olan birşey fakat vakit bulamadığım için bakamıyorum. En kısa sürede eklemeyi düşünüyorum. Şuan için aşağıdaki linkleri inceleyebilirsin.

- (https://github.com/life/il-ilce-mahalle-sokak-cadde-sql)
- (https://github.com/volkansenturk/turkiye-iller-ilceler)

İyi çalışmalar dilerim.

**Comment by yasinatesim** [comment]
Ne yapmak istediğimi pek iyi bir şekilde ifade edememişim, bunu farkettim.

Geliştirmiş olduğunuz bot, Dask'ın sitesindeki(https://adreskodu.dask.gov.tr/) istenen bilgilere göre **adres koduna** erişmemizi sağlıyor. 

İstediğim şey, Dask'ın sitesinden gelen adres kodu.

Yönetim panelinden Dask'ın sitesindeki il, ilçe, mahalle bilgilerine göre **adres kodunu** otomatik oluşturtacağım, amacım tam olarak bu.

Bunun içinde tabiki ilk başta, Dask'ın sitesinde yer alan; il, ilçe, mahalle vb. bilgilerin tamamını alıp bir yere (json) kaydetmem gerekir.

Bu konuda yardımınıza ihtiyacım var.

**Comment by nurullahisik** [comment]
- Bilgileri bir kere kaydedip daha sonra kullanmak istediğinizi anlıyorum.  Bunun için illeri bir kere çekip loop içerisinde ilçe, mahalle-koy, cadde-sokak, bina, kapı ve uavt kodu bilgilerini çekip o şekilde json dosyasına kayıt işlemini gerçekleştirebilirsiniz. Ama bu işlem biraz zaman alabilir ve eğer dask aynı ip den sürekli gelen isteklerde ip adresiniz banlayabilir.

- Çözüm önerisi olarak kullanıcı il seçtiğinde dask'ın sitesine istek atıp ilçeleri, ilçe seçtiğinde tekrar istek atıp mahalle-köyleri vs. bilgilerini adım adım çekip en son uavt kodunu alabilirsiniz.

**Comment by scriptmatik** [comment]
Merhaba öncelikle ellerinize sağlık @nurullahisik json çıktılarındaki türkçe karakter problemlerini giderebilirsen daha sağlıklı bir paylaşım olacağına inanıyorum. Kolay gelsin iyi çalışmalar.

**Comment by nurullahisik** [comment]
@scriptmatik geri bildiriminiz için teşekkür ederim. Türkçe karakter sorunu düzeltilmiştir.

**Comment by scriptmatik** [comment]
@nurullahisik karakter problemi hala devam etmekte hocam. 

$properties = new AddressProperties();
$properties->setId(0);
$properties->setType("cities");

data çıktısı aşağıdaki gibi gözüküyor. 

Array ( [status] => 1 [result] => {"yt":[{"value": "", "text": "SE��N�Z"},{"value": "1","text": "ADANA"},{"value": "2","text": "ADIYAMAN"},{"value": "3","text": "AFYONKARAH�SAR"},{"value": "4","text": "A�RI"},{"value": "68","text": "AKSARAY"},{"value": "5","text": "AMASYA"},{"value": "6","text": "ANKARA"},{"value": "7","text": "ANTALYA"},{"value": "75","text": "ARDAHAN"},{"value": "8","text": "ARTV�N"},{"value": "9","text": "AYDIN"},{"value": "10","text": "BALIKES�R"},{"value": "74","text": "BARTIN"},{"value": "72","text": "BATMAN"},{"value": "69","text": "BAYBURT"},{"value": "11","text": "B�LEC�K"},{"value": "12","text": "B�NG�L"},{"value": "13","text": "B�TL�S"},{"value": "14","text": "BOLU"},{"value": "15","text": "BURDUR"},{"value": "16","text": "BURSA"},{"value": "17","text": "�ANAKKALE"},{"value": "18","text": "�ANKIRI"},{"value": "19","text": "�ORUM"},{"value": "20","text": "DEN�ZL�"},{"value": "21","text": "D�YARBAKIR"},{"value": "81","text": "D�ZCE"},{"value": "22","text": "ED�RNE"},{"value": "23","text": "ELAZI�"},{"value": "24","text": "ERZ�NCAN"},{"value": "25","text": "ERZURUM"},{"value": "26","text": "ESK��EH�R"},{"value": "27","text": "GAZ�ANTEP"},{"value": "28","text": "G�RESUN"},{"value": "502","text": "G�RNE (KIBRIS)"},{"value": "29","text": "G�M��HANE"},{"value": "30","text": "HAKKAR�"},{"value": "31","text": "HATAY"},{"value": "76","text": "I�DIR"},{"value": "32","text": "ISPARTA"},{"value": "34","text": "�STANBUL"},{"value": "35","text": "�ZM�R"},{"value": "46","text": "KAHRAMANMARA�"},{"value": "78","text": "KARAB�K"},{"value": "70","text": "KARAMAN"},{"value": "36","text": "KARS"},{"value": "37","text": "KASTAMONU"},{"value": "38","text": "KAYSER�"},{"value": "71","text": "KIRIKKALE"},{"value": "39","text": "KIRKLAREL�"},{"value": "40","text": "KIR�EH�R"},{"value": "79","text": "K�L�S"},{"value": "41","text": "KOCAEL�"},{"value": "42","text": "KONYA"},{"value": "43","text": "K�TAHYA"},{"value": "501","text": "LEFKO�E (KIBRIS)"},{"value": "503","text": "MA�USA (KIBRIS)"},{"value": "44","text": "MALATYA"},{"value": "45","text": "MAN�SA"},{"value": "47","text": "MARD�N"},{"value": "33","text": "MERS�N"},{"value": "48","text": "MU�LA"},{"value": "49","text": "MU�"},{"value": "50","text": "NEV�EH�R"},{"value": "51","text": "N��DE"},{"value": "52","text": "ORDU"},{"value": "80","text": "OSMAN�YE"},{"value": "53","text": "R�ZE"},{"value": "54","text": "SAKARYA"},{"value": "55","text": "SAMSUN"},{"value": "56","text": "S��RT"},{"value": "57","text": "S�NOP"},{"value": "58","text": "S�VAS"},{"value": "63","text": "�ANLIURFA"},{"value": "73","text": "�IRNAK"},{"value": "59","text": "TEK�RDA�"},{"value": "60","text": "TOKAT"},{"value": "61","text": "TRABZON"},{"value": "62","text": "TUNCEL�"},{"value": "64","text": "U�AK"},{"value": "65","text": "VAN"},{"value": "77","text": "YALOVA"},{"value": "66","text": "YOZGAT"},{"value": "67","text": "ZONGULDAK"}]} [message] => )

ayrıca AddressInitialize.php sayfasındaki return AddressMapper::create($result['result'])->jsonDecode()->mapAddressResource(new AddressInitialize()); bu satırda da problem var. 

çıktıyı kodun önüne print_r($result); yazarak alıyorum. tekrar kolay gelsin.

**Comment by nurullahisik** [comment]
- composer require nurullah/uavt-adres-kodu bu şekilde projeyi tekrar indirmeyi deneyebilir misiniz?

**Comment by scriptmatik** [comment]
güncellemeden sonra tekrar söylediğin gibi indirdim yorumu o sonuçlara göre yazdım hocam.

**Comment by nurullahisik** [comment]
Composer da güncellemeyi yapmamısım. ondan kaynaklı sorun devam etmiş olabilir. V1.1 de sorunu değişiklikleri görüntüleyebilirsiniz., https://github.com/nurullahisik/php-uavt-adreskodu-botu/releases/tag/V1.1

**Comment by scriptmatik** [comment]
tamamdır hocam eline emeğine sağlık problem düzeldi :)  info@scriptmatik.com adresine bir mail gönderirmisin tanışalım.
