### ISSUE TITLE
Karakter Hatası

### ISSUE THREAD

**Issue by ckiyici** [nurullahisik/php-uavt-adreskodu-botu#2]
Readme.md'deki bina örneğinde karakter hatası var. "DENÝZKENT SÝTESÝ" şeklinde dönmekte. Dosyayı farklı karakter setlerinde kaydetsemde düzelmedi. İl ve İlçe'de problem yok. Elle düzeltme gerekiyor.

$properties = new AddressProperties();
$properties->setId(359820);
$properties->setType("building");

**Comment by nurullahisik** [comment]
Dask'ın sitesinde yapılan güncellemeden kaynaklı türkçe karakter ve uavt kodu sorunu oluştu. Şuan gerekli düzenlemeleri yaptım. Tekrardan proje çekerseniz sorun giderilmiş olacaktır.

**Comment by ckiyici** [comment]
Teşekkürler
