### ISSUE TITLE
İç Kapı UAVT kodları ve Karakter hatası

### ISSUE THREAD

**Issue by ckiyici** [nurullahisik/php-uavt-adreskodu-botu#3]
Readme.md'deki örnekte uavt kodu boş gelmekte ve door_number değerinde karakter hatası mevcut.

[uavt] =>
--
  | [door_number] => SEÃ
  | [type] => 1

$properties = new AddressProperties();
$properties->setId(20007131);
$properties->setType("door");

**Comment by nurullahisik** [comment]
Dask'ın sitesinde yapılan güncellemeden kaynaklı türkçe karakter ve uavt kodu sorunu oluştu. Şuan gerekli düzenlemeleri yaptım. Tekrardan proje çekerseniz sorun giderilmiş olacaktır.

**Comment by ckiyici** [comment]
Teşekkürler
