### ISSUE TITLE
mahalle seçtikten sonra cadde sokak seçim gelmemesi

### ISSUE THREAD

**Issue by mrtkhrmn82** [nurullahisik/php-uavt-adreskodu-botu#4]
nurullah merhaba,

il, ilçe, köy bucak ve mahalle seçtiriyorum select olarak geliyor bir problem yok fakat cadde kısmı table olduğundan mıdır nedir bilemedim getiremiyorum. 

örneklendirmem gerekirse il seçmek için 

  <select id="optionA" onchange="ildenilcesec(this.value)">
      <option>Select an Option...</option>
      <?php
      $properties = new AddressProperties();
      $properties->setId(0);
      $properties->setType("cities");
      $IlSonuc = $object::create($properties)->getResult();
      foreach ($IlSonuc as $row) {
          echo "<option value='{$row->value}'>{$row->text}</option>";
      }
      ?>
  </select>

javascript ile
     xmlhttp.open("GET","ildenilcesec.php?opt="+str, true);

demo sayfasına gönderiyorum ve hangi ili seçtiysem ordan gelen ilçe listesini 

 <select id="ilcelistesi" onchange="ilcedenkoybucaksec(this.value)">
    <option>Select an Option...</option>
  </select>

bu şekilde alarak köy bucak kısmına geçebiliyorum. taki mahalle seçip cadde alamayana kadar. mahalleyi seçtikten sonra cadde sokak dönüşlerini nasıl listeleyebilirim ? desteğini beklerim.

hiç bir hiyerarşiye sokmadan 

    $properties = new AddressProperties();
    $properties->setId(176887);
    $properties->setType("street");

    $sonuc = $object::create($properties)->getResult();
?>
<table>
    <tr>
        <td>ad</td>
        <td>ad</td>
    </tr>
    <?php
    foreach ($sonuc as $row) {
        echo "<tr>
            <td>{$row->value}</td>
            <td>{$row->text}</td>
        </tr>";
    }
    ?>
    </table>

ile döndürsemde 

Notice: Undefined property: stdClass::$value in /home/mknettr/public_html/abc/yani0.php on line 29

Notice: Undefined property: stdClass::$text in /home/mknettr/public_html/abc/yani0.php on line 30

olarak value ve text için tanımsız diyor.

**Comment by nurullahisik** [comment]
servislerin donus degerleri farklı olarak gelmektedir. il ilcede value-text seklinde donerken cadde de id-name-type olarak donmektedir. Aşağıdaki sekilde sonucu gorebilirsiniz. 

$properties = new AddressProperties();
$properties->setId(176887);
$properties->setType("street");

$result = $object::create($properties)->getResult();

foreach($result as $item){
	echo "id = " . $item->id . " - " . " name = " . $item->name . " - " . "type = " . $item->type;
	echo "<br>";
}

**Comment by mrtkhrmn82** [comment]
evet hocam doğru atlamışım o çıktıyı :) 
onları hallettim fakat daire no seçtiğimde sonucu getirmiyor. siteye baktığımda bot değilim uygulaması var ona mı takılıyor acaba nasıl aşabiliriz ?

**Comment by nurullahisik** [comment]
dask'ın sitesinde servis guncellemeleri olmus bir sure once, dün o sorunu düzelttim. Eğer dünden önce repoyu çektiyseniz bu sorunla karsılasmanız normal. Paketi güncellerseniz sorununuz düzelecektir.

**Comment by mrtkhrmn82** [comment]
PS D:\xampp\htdocs\php-uavt-adreskodu-botu-master> composer require nurullah/uavt-adres-kodu
Using version ^1.2 for nurullah/uavt-adres-kodu
Root package 'nurullah/uavt-adres-kodu' cannot require itself in its composer.json
PS D:\xampp\htdocs\php-uavt-adreskodu-botu-master>

composer, visual code studio içindeki terminal, windows powershell ile de denedim aynı hata

**Comment by nurullahisik** [comment]
composer update komutunu dener misin

**Comment by mrtkhrmn82** [comment]
PS D:\xampp\htdocs\adres> composer update
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 0 updates, 1 removal
  - Removing nurullah/uavt-adres-kodu (V1.1)
Generating autoload files

1.1i sildi yenisini yüklemedi :)
composer require nurullah/auvt-adres-kodu denedim olmadı yine

**Comment by nurullahisik** [comment]
herhangi bir sorun olmaması lazım ama. composer.json dosyasında paketin adını silip tekrardan **composer require nurullah/auvt-adres-kodu** bu komutu calıstırabilir misin

**Comment by mrtkhrmn82** [comment]
name alanını sildikten sonra oldu şimdide iç kapı seçtiğimde 

Notice: Undefined index: REQUEST_SCHEME in /home/mknettr/public_html/abc/vendor/nurullah/uavt-adres-kodu/src/Curl.php on line 71

Notice: Undefined index: REQUEST_SCHEME in /home/mknettr/public_html/abc/vendor/nurullah/uavt-adres-kodu/src/Curl.php on line 71

Notice: Undefined index: REQUEST_SCHEME in /home/mknettr/public_html/abc/vendor/nurullah/uavt-adres-kodu/src/Curl.php on line 71

olarak dönüyor

**Comment by nurullahisik** [comment]
https://github.com/nurullahisik/php-uavt-adreskodu-botu/issues/5#issuecomment-533861775

**Comment by nurullahisik** [comment]
Curl.php dosyasında certificate metodunu aşağıdaki gibi güncellersen local ortamda da sorunun hal olacaktır. 

```
private function certificate(& $options)
{
        $options[CURLOPT_SSL_VERIFYPEER] = false;
        $options[CURLOPT_SSL_VERIFYHOST] = false;

        return $options;
}
```

**Comment by mrtkhrmn82** [comment]
şuanda iç kapı no seçtiğimde uavt kodu gelmiyor. sadece bu iki değer dönüyor. 

{$row->type} - {$row->door_number}

**Comment by mrtkhrmn82** [comment]
tamamdır dönen veriyi {$row->uavt} - {$row->door_number} olarak güncelledim sorun kalmadı. teşekkür ederim.
