### ISSUE TITLE
Undefined index: REQUEST_SCHEME

### ISSUE THREAD

**Issue by ckiyici** [nurullahisik/php-uavt-adreskodu-botu#5]
İl numaralarına göre ilçeleri çağırdığımda aşağıdaki hata konsolda görünüyor ancak veri çekmede bir problem yok.
`
PHP Notice:  Undefined index: REQUEST_SCHEME in D:\xampp\htdocs\vendor\nurullah\uavt-adres-kodu\src\Curl.php on line 71

Notice: Undefined index: REQUEST_SCHEME in D:\xampp\htdocs\vendor\nurullah\uavt-adres-kodu\src\Curl.php on line 71
PHP Notice:  Undefined index: REQUEST_SCHEME in D:\xampp\htdocs\vendor\nurullah\uavt-adres-kodu\src\Curl.php on line 71

Notice: Undefined index: REQUEST_SCHEME in D:\xampp\htdocs\vendor\nurullah\uavt-adres-kodu\src\Curl.php on line 71
PHP Notice:  Undefined index: REQUEST_SCHEME in D:\xampp\htdocs\vendor\nurullah\uavt-adres-kodu\src\Curl.php on line 71

Notice: Undefined index: REQUEST_SCHEME in D:\xampp\htdocs\vendor\nurullah\uavt-adres-kodu\src\Curl.php on line 71`

**Comment by nurullahisik** [comment]
consoledan uygulamayı calıstırdıgında veya php -S localhost:port komutu ile calıstırdıgında uygulama server değişkenleri atanamadıgından o uyarıyı vermesi normal. sunucuda bu sorunla karsılasmayacaksın.
