### ISSUE TITLE
Cadde Sokak Problemi

### ISSUE THREAD

**Issue by keakarsu** [nurullahisik/php-uavt-adreskodu-botu#6]
Merhaba,

İl, ilçe ve mahalleleri çekebiliyorum ancak sokak, bina ve kapı numaralarını çekemiyorum. Serviste bir değişiklik olabilir mi ya da şuan da siz çekebiliyor musunuz?

Teşekkürler.

**Comment by nurullahisik** [comment]
Verdiğim örneklerde cadde/sokak, bina ve kapıyı çekebiliyorum. Siz hangi id ile deniyorsunuz? Paylasabilirseniz yardımcı olabilirim.

**Comment by keakarsu** [comment]
Tamamdır, benden kaynaklı bir problemden dolayı çekememişim. Desteğinize ve ilginize çok teşekkürler.

NURULLAH IŞIK <notifications@github.com> şunları yazdı (5 Kas 2019 14:07):

﻿

Verdiğim örneklerde cadde/sokak, bina ve kapıyı çekebiliyorum. Siz hangi id ile deniyorsunuz? Paylasabilirseniz yardımcı olabilirim.
