### ISSUE TITLE
Gelmeyen İçerik Sorunu

### ISSUE THREAD

**Issue by sdertli** [nurullahisik/php-uavt-adreskodu-botu#8]
Merhabalar,

Bazı bölge içerikleri gelmiyor. 

Adana / Çukurova / Merkez / Belediye Evleri 

sokak ve dolayısıyla diğer kısımlar çıkmıyor. Bunun gibi rastgele denerken denk geldiğim benzer durumlar var.

dask sayfasında da benzer şekilde. Daskta reel bir değer aradığında karşılığı var örneğin 840001 sk. arayınca çıkıyor. Bu veriler erişilmez değil ancak, default olarak listeleme yapmıyor. (custom.js de yt değerinde sorun çıkarıyor. consol da görünüyor.

https://adres.nvi.gov.tr/VatandasIslemleri/AdresSorgu da liste halinde çıkıyor.

**Comment by sdertli** [comment]
Diğer sorgu sitelerini de inceledim bu arada çoğunda sorunsuz listeleniyor.

https://www.quicksigorta.com/adres-kodu-sorgulama

**Comment by nurullahisik** [comment]
Merhaba,

Evet bu sorun uzun süredir dask'ın sisteminde bulunuyor. Listeleme kısmında sorgu 500 hatasına düşüyor. Arama yapıldığında bazı durumlar için veri geliyor ancak bazı durumlarda 500 hatası veriyor. Belirttiğiniz adres için bina adı veya numarasına göre arama yapıldığında veriler listeleniyor ancak cadde/sokak bilgisine göre aramada 500 hatası veriyor.
( Direk dask'ın listeleme servisinde 500 hatası var js veya gönderilen ile alakalı bir durum değil. )

Bot dask sistemini kullandığı için burada yapabileceğim bir şey bulunmuyor. Fırsatım olursa arama kısmını eklemeye çalışırım. Ancak buda kesin bir çözüm olmaz. Dask sisteminin bu sorunu çözmesi gerekecek. 

Diğer sorgu siteleri tahminimce NVI veya TKGM altyapısını kullanıyor.

**Comment by sdertli** [comment]
Aynen söylediğiniz gibi. 

Peki sistemi NVI tarafından çekmeye entegre etmek çok mu zor olurdu? Yada onla izin vermiyorlar mıdır bu tarz bir erişime?

**Comment by nurullahisik** [comment]
NVI'den verileri çekmek için kodları baştan yazmak gerekir. Bunda NVI'nin aldığı güvenlik önemleri de önemli analiz etmek gerekiyor siteyi.
