### ISSUE TITLE
index.php hatası

### ISSUE THREAD

**Issue by sedatigrek** [nurullahisik/php-uavt-adreskodu-botu#9]
Merhabalar,

Ben dosyaları localhost a yükledim ve çalıştırdım, ancak index.php de hata veriyor

4 - include __DIR__.'/vendor/autoload.php';

10 - $object = new AddressInitialize();

**Comment by nurullahisik** [comment]
Merhaba,

autoload.php dosyasının path i hatalı. proje dizininize göre include kısmını düzenlemeniz gerekmektedir.

Örn:
include $_SERVER["DOCUMENTROOUT"] . '/vendor/autoload.php';
